<?php

require_once '../AnafInvoice.php';
require_once '../UBLStructure.php';
include_once '../Constants.php';

use PHPUnit\Framework\TestCase;

class AnafInvoiceTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->anafRest = new AnafInvoice( __DIR__.'factura_1.xml', 1);
        $this->XMLText = new UBLStructure();
    }

    public function testAnafRestConstruct()
    {
        $this->assertEquals('111118', $this->anafRest->getVat());
        $this->assertEquals('XXXXXXXY', $this->anafRest->getClientId());
        $this->assertEquals('https://www.sabeeapp.com/', $this->anafRest->getRedirectUri());

    }
    public function testTokenFromAnafIsReturned()
    {
        $this->anafRest->getTokenAnaf();
       //$this->assertContains('error', $token);

    }

    public function testUBLStructure()
    {
        $invoice['DisplayedNumber']='123456';
        $this->XMLText->AnafExport('', $invoice);




    }

}
