<?php
const API_BASE_URL = 'https://api.anaf.ro/';
const PUBLIC_API_BASE_URL = 'https://webservicesp.anaf.ro/';
const API_BASE_PATH_SANDBOX = 'test/';
const API_BASE_SANDBOX = API_BASE_URL.API_BASE_PATH_SANDBOX;
const API_BASE_PATH_PROD = 'prod/';
const API_BASE_PROD = API_BASE_URL.API_BASE_PATH_PROD;
const PUBLIC_API_BASE_PATH_PROD = 'prod/';
const PUBLIC_API_BASE_PROD = PUBLIC_API_BASE_PATH_PROD.PUBLIC_API_BASE_PATH_PROD;



