<?php

require_once 'AnafRest.php';
include_once 'Constants.php';

use PHPUnit\Framework\TestCase;

class AnafRestTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->anafRest = new AnafRest( 'path_to_XML_UBI', 1);

    }

    public function testAnafRestConstruct()
    {
        $this->assertEquals('111118', $this->anafRest->getVat());
        $this->assertEquals('XXXXXXXY', $this->anafRest->getClientId());
        $this->assertEquals('https://www.sabeeapp.com/', $this->anafRest->getRedirectUri());

    }
    public function testTokenFromAnafIsReturned()
    {
        $this->anafRest->getTokenAnaf();
       //$this->assertContains('error', $token);

    }

}
